name: Serverless Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: npm ci
    - run: npx serverless deploy -s prod --app bikehero --org personal --database-url ${{ secrets.DATABASE_URL }} --append-plugins='@graphile/postgis @graphile-contrib/pg-simplify-inflector'
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
